import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import SideMenu from "@/components/SideMenu";

export const metadata: Metadata = {
  title: "Test-UltraData",
  description: "Generated by Hanis A. Salam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Header */}
        <Header />

        <section className="flex flex-row">
          <div className="w-26 bg-gray-500 text-white p-4 hidden lg:flex md:flex">
            {/* side menu */}
            <SideMenu />
          </div>
          <div className="flex-1">
            {/* main */}
            {children}
          </div>
        </section>
      </body>
    </html>
  );
}
